plugins:
  - serverless-esbuild

custom:
  secrets: ${file(./config/${opt:stage, 'dev'}.json)}

service: ${self:custom.secrets.service.name}

frameworkVersion: "3"

provider:
  name: ${self:custom.secrets.provider.name}
  runtime: ${self:custom.secrets.provider.runtime}
  stage: ${self:custom.secrets.provider.stage, 'dev'}
  region: ${self:custom.secrets.provider.region}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    BOT_NAME: ${self:custom.secrets.provider.environment.BOT_NAME}-${self:provider.stage}
    TELEGRAM_SEND_MESSAGE_URL: ${self:custom.secrets.provider.environment.TELEGRAM_SEND_MESSAGE_URL}
    MONGO_USER: ${self:custom.secrets.provider.environment.MONGO_USER}
    MONGO_PASSWORD: ${self:custom.secrets.provider.environment.MONGO_PASSWORD}
    MONGO_HOST: ${self:custom.secrets.provider.environment.MONGO_HOST}
    MONGO_DATABASE: ${self:custom.secrets.provider.environment.MONGO_DATABASE}
    USERNAME: ${self:custom.secrets.provider.environment.USERNAME}
    PASSWORD: ${self:custom.secrets.provider.environment.PASSWORD}

functions:
  crews: ${file(./src/functions/crews/function.yml)}
  crew: ${file(./src/functions/crew/function.yml)}
  crewsCreate: ${file(./src/functions/crews_create/function.yml)}
  crewsMembersAdd: ${file(./src/functions/crews_members_add/function.yml)}
  crewsMembersRemove: ${file(./src/functions/crews_members_remove/function.yml)}
