plugins:
  - serverless-esbuild

custom:
  secrets: ${file(./config/${opt:stage, 'dev'}.json)}

service: ${self:custom.secrets.service.name}

frameworkVersion: "3"

provider:
  name: ${self:custom.secrets.provider.name}
  runtime: ${self:custom.secrets.provider.runtime}
  stage: ${self:custom.secrets.provider.stage, 'dev'}
  region: ${self:custom.secrets.provider.region}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    BOT_NAME: ${self:custom.secrets.provider.environment.BOT_NAME}-${self:provider.stage}
    TELEGRAM_BOT_TOKEN: ${self:custom.secrets.provider.environment.TELEGRAM_BOT_TOKEN}

functions:
  telegramSetWebhook: ${file(./src/functions/telegram_set_webhook/function.yml)}
  telegramWebhook: ${file(./src/functions/telegram_webhook/function.yml)}
